- hosts: cassandra
  become: yes
  gather_facts: yes
  tasks:
    # Start Kafka UI
    - name: start agent
      docker_container:
        name: kafka_ui
        image: provectuslabs/kafka-ui:v0.7.2
        state: started
        ports:
          - "8086:8080"
        restart: yes
        restart_policy: always
        env:
          AUTH_TYPE: "LOGIN_FORM"
          SPRING_SECURITY_USER_NAME: admin
          SPRING_SECURITY_USER_PASSWORD: "{{ admin_password }}"
          DYNAMIC_CONFIG_ENABLED: 'true'
          KAFKA_CLUSTERS_0_NAME: "fde-kafka-{{ cluster_id }}"
          KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "{{ host_test }}:9092"
          KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_PLAINTEXT
          KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: PLAIN
          KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="{{ admin_password }}";'
        cpus: 0.5
        memory: 256M
        log_driver: json-file
        log_options:
          max-size: "15m"